apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: rest
spec:
  selector:
    matchLabels:
      app: rest
  replicas: 1
  template:
    metadata:
      labels:
        app: rest
    spec:
      containers:
      - name: master
        image: sahathyadi/demucs-rest
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: FLASK_HOST
          value: "0.0.0.0"
        - name: FLASK_PORT
          value: "5000"
        - name: "MINIO_ENDPOINT"
          value: "minio-proj.minio-ns.svc.cluster.local:9000"
        - name: "MINIO_ACCESS_KEY"
          value: "rootuser"
        - name: "MINIO_SECRET_KEY"
          value: "rootpass123"